version: "3.9"

services:
  postgis:
    container_name: gis_postgis
    build: ./
    image: gis_postgis
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=gaiaDB
    volumes:
      - pgdata:/var/lib/postgresql/data
    
volumes:
  pgdata:
    name: gis_pgdata