---
title: "example_execution"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{example_execution}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(rjson)
library(dplyr)
library(sf)
library(DatabaseConnector)
library(rpostgis)
library(plyr)
library(tibble)
```

```{r, eval=FALSE}
connectionDetails <- DatabaseConnector::createConnectionDetails(
  dbms = "postgresql",  # options: oracle, postgressql, redshift, sql server, pdw, netezza, bigquery, sqlite
  server = "", # name of the server
  port = 5433,
  user="postgres", # username to access server
  password = "") #password for that user

# Run the backbone_ddl.sql file

conn <- DatabaseConnector::connect(connectionDetails)
DatabaseConnector::executeSql(conn, sql = readr::read_file(system.file("sql", "backbone_ddl.sql", package="GIS")))

# Import data_source and variable_source contents from CSV
dataSource <- read.csv(system.file("extdata", "data_source.csv", package="GIS"))
variableSource <- read.csv(system.file("extdata", "variable_source.csv", package="GIS"))
DatabaseConnector::dbWriteTable(conn, "backbone.data_source", dataSource, row.names = FALSE, append = TRUE)
DatabaseConnector::dbWriteTable(conn, "backbone.variable_source", variableSource, row.names = FALSE, append = TRUE)


# Populate the geom_index and attr_index
createIndices(get_uuids())

importedShapeFile <- importShapefile(connectionDetails, variableSourceId = 157)
disconnect(conn)
```
