on: 
  push:
    paths:
      - 'rmd/**'
      - 'packages/gaiaCore/man/**'

name: render R Markdown files to docs

jobs:
  render:
    name: render RMD and build pkgdown site 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-tinytex@v2
      - name: Install rmd depedencies  
        run: |
          Rscript -e "install.packages('rmarkdown')"
      - name: render all rmd 
        run: |
          Rscript -e "rmarkdown::render_site('rmd/')"
      - name: Install rmd depedencies  
        run: |
          Rscript -e "install.packages('pkgdown')"
      - name: build pkgdown site
        run: |
          Rscript -e "pkgdown::build_site('packages/gaiaCore/man/')"